### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by abdymm** [abdymm/Android-CSV#1]
- [x] Key value data  ,ex. Nama : abdy
- [ ] Manual data not from list of object , just a string
- [ ] code generation
- [x] New line
- [x] clear csv
- [ ]  import from db 
- [ ] Custom header
